title: CMPD6
preposition: at
description: >-
  Computational and Mathematical Population Dynamics 6, Winnipeg, Manitoba, Canada, 23-27 May 2023.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cmpd6.github.io" # the base hostname & protocol for the site

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/
  information:
    output: true
    permalink: /:collection/:title/
  minisymposia:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: minisymposia
    values:
      layout: minisymposium
  - scope:
      path: ""
      type: rooms
    values:
      layout: room
  - scope:
      path: ""
      type: informations
    values:
      layout: information


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: CMPD6
      img: 'SkylineWinnipgeShortScaledTitle.png'
      url: 'https://cmpd6.github.io/'
    links:
      - name: Committees
        relative_url: "/committees.html"
      - name: Minisymposia
        relative_url: /minisymposia/
        layout: minisymposia-overview
      - name: Speakers
        relative_url: /speakers/
        layout: speaker-overview
      - name: Talks
        relative_url: /talks/
      - name: Program
        relative_url: /program/
      - name: Rooms
        relative_url: /rooms/
      - name: Information
        relative_url: /information/
      - name: Previous Editions
        menu:
          - name: 2023 (current)
            disabled: true
          - name: 2019
            absolute_url: "http://www.math.fau.edu/cmpd5/"
          - name: 2013
            absolute_url: "https://www.math.miami.edu/~ruan/CMPD4.pdf"
          - name: History
            absolute_url: "/CMPD_history.html"


  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: true
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'SkylineWinnipgeLong.png'
    links:
      #- name: Program
      #  relative_url: /program/
      #- name: How to get there
      #  relative_url: /venue/

  # Information boxes
  info_bars:
    - title: Computational and Mathematical Population Dynamics 6 (CMPD6), Winnipeg, 23-27 May 2023
      color: primary
      main_only: true
    - text: This is just some random content for testing purposes.
      color: warning
      pages_only: true

  # Live indications
  live:
    date: 23.05.2023
    timezone: GMT-7
    stop:       240  # in minutes
    streaming:
      enable: false
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 49.8075008, -97.1366259
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Plenaries
        color: info
      - name: Minisymposium lectures
        color: success
      - name: Contributed talks
        color: dark
      - name: Breaks
        color: warning

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: false

  information:
    # Disable links to information?
    hide: false
    # URL of information page
    url: '/information'
    # Main page title shown on information navigation bar
    navbar_title: 'Information'
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: '/program'
    # Time steps in program table
    time_steps: 30 # in minutes
    # Show intermediary time steps (next to full hours)
    show_alltimes: true

